/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Divider: typeof import('primevue/divider')['default']
    Form: typeof import('@primevue/forms/form')['default']
    Image: typeof import('primevue/image')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleComponents: typeof import('./src/components/SampleComponents.vue')['default']
    Select: typeof import('primevue/select')['default']
    Step: typeof import('primevue/step')['default']
    StepList: typeof import('primevue/steplist')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TemplateCreate: typeof import('./src/components/TemplateCreate.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    UiAdvanceFilter: typeof import('./src/components/UiAdvanceFilter.vue')['default']
    UiCard: typeof import('./src/components/UiCard.vue')['default']
    UiCardHeader: typeof import('./src/components/UiCardHeader.vue')['default']
    UiConfirmDialog: typeof import('./src/components/UiConfirmDialog.vue')['default']
    UiFormGroup: typeof import('./src/components/UiFormGroup.vue')['default']
    UiPercentage: typeof import('./src/components/UiPercentage.vue')['default']
    UiSearch: typeof import('./src/components/UiSearch.vue')['default']
    UiSidebarMenu: typeof import('./src/components/UiSidebarMenu.vue')['default']
    UiSidebarMenuItem: typeof import('./src/components/UiSidebarMenuItem.vue')['default']
    UiSidebarMenuSectionHeader: typeof import('./src/components/UiSidebarMenuSectionHeader.vue')['default']
    UiSidebarOutlet: typeof import('./src/components/UiSidebarOutlet.vue')['default']
    UiSidebarProfile: typeof import('./src/components/UiSidebarProfile.vue')['default']
    UiSidebarSubmenuContainer: typeof import('./src/components/UiSidebarSubmenuContainer.vue')['default']
    UiSwitch: typeof import('./src/components/UiSwitch.vue')['default']
    UiToast: typeof import('./src/components/UiToast.vue')['default']
    UiWrapIcon: typeof import('./src/components/UiWrapIcon.vue')['default']
  }
}
